"""empty message

Revision ID: 68bd28e20af1
Revises: a5cffa318ac2
Create Date: 2024-07-22 18:19:15.404535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bd28e20af1'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=100), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=100), nullable=True),
    sa.Column('terrain', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('planet_id')
    )
    op.create_table('characters',
    sa.Column('characters_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('character_weight', sa.String(length=100), nullable=True),
    sa.Column('character_hair_color', sa.String(length=20), nullable=True),
    sa.Column('character_eye_color', sa.String(length=20), nullable=False),
    sa.Column('character_birth_year', sa.Integer(), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planet.planet_id'], ),
    sa.PrimaryKeyConstraint('characters_id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.characters_id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.planet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('favorites')
    op.drop_table('characters')
    op.drop_table('planet')
    # ### end Alembic commands ###
