"""empty message

Revision ID: afc03678fe52
Revises: 68bd28e20af1
Create Date: 2024-07-23 17:05:52.206969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc03678fe52'
down_revision = '68bd28e20af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
